### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by Dieforrobux** [Dieforrobux/Chat-room.#1]
Hello _everyone_! 

So i decided to make a chat room. Weird huh?

Yeah, Because you can't **chat** on **github.** Boring eh. Oh, I know what your thinking. I will just invite you to a **chat room** so we can chat not on github!

Nope, Sorry. But i just have a **chromebook**. Its managed by [Bcps (Baltimore County Public Schools)](https://bcps.org)
The people that manage it have blocked certain websites. Such as games websites. Chat rooms. And meeting websites. 

So come on, What you waiting for. Send a _message!_

**Comment by ghost** [comment]
My school chromebook is managed my the Beaverton School District, which has the relay chrome extension allowing them to see all my activity in real-time and block sites

**Comment by Dieforrobux** [comment]
same but i have different school

**Comment by Dieforrobux** [comment]
chat room:http://turbowarp.org/481990992/

**Comment by ghost** [comment]
how to chat

**Comment by ghost** [comment]
nvm

**Comment by Dieforrobux** [comment]
> how to chat

ok to chat rn?

**Comment by ghost** [comment]
> same but I have different school

![image](https://user-images.githubusercontent.com/64666021/106629690-52ffc580-6538-11eb-9cc4-a763a93af705.png)
does it look like this>

**Comment by Dieforrobux** [comment]
VERY CLOSE!!!!!!!! ITS JUST YELLOW
i can't show mine it does work for some reason

**Comment by ghost** [comment]
follow me on scratch

**Comment by Dieforrobux** [comment]
wait what

**Comment by ghost** [comment]
ok

**Comment by Dieforrobux** [comment]
STOP!!!

**Comment by ghost** [comment]
@AmpersandGD LOOK UP

> I DIDN'T SAY THAT DUDE

**Comment by ghost** [comment]
Bruh, please stop

**Comment by Dieforrobux** [comment]
ok

**Comment by Dieforrobux** [comment]
_**https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489https://github.com/Dieforrobux/Chat-room./issues/1#issuecomment-772784489**_

**Comment by Dieforrobux** [comment]
Chat at #3
